name: Conservatives
description: This demo is to show a proof-of-concept
author: Conservatives
date: '2020-08-11T17:40:00.839Z'
prototype_version: 2.0
specification_version: 1.0

runtimes:
  kernel: python3


tasks:
  - type: run_session
    name: Install dependencies
    script: scripts/install_dependencies.py
    kernel: python3
    cpu: 2
    memory: 4

  - type: run_session
    name: Train model
    script: scripts/run_scripts.py
    kernel: python3
    cpu: 2
    memory: 8

  - type: start_application
    name: Start application
    script: scripts/launch_app.py
    kernel: python3
    cpu: 2
    memory: 8
